app/models.py
from . import db


class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    users = db.relationship('User', backref='role', lazy='dynamic')

    def __repr__(self):
        return '<Role %r>' % self.name


class User(db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True, index=True)
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))

    def __repr__(self):
        return '<User %r>' % self.username

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField
from wtforms.validators import DataRequired


class NameForm(FlaskForm):
    name = StringField('What is your name?', validators=[DataRequired()])
    submit = SubmitField('Submit')

class FieldForm(FlaskForm):
    # need to chnge to api
    STARS_FIELD = [
        ("AC_8_Campus_As_A_Living_Laboratory", "AC-8 Campus As A Living Laboratory"),
        ("AC_9_Research_and_Scholarship", "AC-9 Research and Scholarship"),
        ("EN_14_Participation_in_Public_Policy", "EN-14 Participation in Public Policy"),
        ("OP_10_Biodiversity", "OP-10 Biodiversity"),
        ("PA_1_Sustainability_Coordination", "PA-1 Sustainability Coordination")
    ]
    field = SelectField('STARS Field', choices=STARS_FIELD)
    submit = SubmitField('Submit')  

class SearchForm(FieldForm):
    query = StringField('Keyword')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_mail import Mail
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from config import config

bootstrap = Bootstrap()
mail = Mail()
moment = Moment()
db = SQLAlchemy()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    db.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
#3rd
from dataclasses import field
from flask import render_template, request, redirect, url_for
import requests

#local
from config import config
from .. import db
from ..models import User
from ..email import send_email
from . import main
from .forms import FieldForm, SearchForm
import app.service.text_cloud as tc
import os
from app.service import cos_sim as cs

API_ROOT = config[os.getenv('FLASK_CONFIG') or 'default'].FLASK_API

@main.route("/", methods=["GET", "POST"])
def index():
    return render_template("index.html")

@main.route("/function_index", methods=["GET", "POST"])
def function_index():
    return render_template("function_index.html")

@main.route("/rank", methods=["GET", "POST"])
def rank():
    form = FieldForm()
    if request.method == "POST":
        if form.validate_on_submit():
            field = form.field.data
            return redirect(url_for("main.rank_field", field=field))
    return render_template("rank.html", form=form)

@main.route("/rank/<string:field>", methods=["GET"])
def rank_field(field):
    api_path = API_ROOT+f"v1/rank"
    params = {
        "field": field,
    }
    response = requests.get(api_path, params = params)
    rank_result = response.json()

    return render_template("rank_field.html", field = field, rank_result = rank_result)

@main.route("/text_cloud", methods=["GET", "POST"])
def text_cloud():
    form = FieldForm()
    if request.method == "POST":
        if form.validate_on_submit():
            field = form.field.data
            return redirect(url_for("main.text_cloud_field", field=field))
    return render_template("text_cloud.html", form=form)

@main.route("/text_cloud/<string:field>", methods=["GET"])
def text_cloud_field(field):
    api_path = API_ROOT+f"v1/textcloud"
    params = {
        "field": field,
    }
    response = requests.get(api_path, params = params)
    result_dict = response.json()
    result = tc.GenerateTfIdfTag.transform_tag(result_dict)
    return render_template("text_cloud_field.html", field = field, result = result)

@main.route("/cos_sim", methods=["GET", "POST"])
def cos_sim():
    search_form = SearchForm()
    if request.method == "POST":
        if (search_form.validate_on_submit()):
            field = search_form.field.data
            query = search_form.query.data
            return redirect(url_for("main.cos_sim_field", field=field, query = query))

    return render_template("cos_sim.html", search_form=search_form)

@main.route("/cos_sim/<string:field>/<string:query>", methods=["GET"])
#http://127.0.0.1:3030/cos_sim/en_14_participation_in_public_policy/condit
def cos_sim_field(field, query):
    api_path = API_ROOT+f"v1/cos_sim"
    params = {
        "field": field,
        "query": query
    }
    response = requests.get(api_path, params = params)
    result = response.json()

    field_result = params["field"].replace("_", " ")

    score_object = cs.CosSimResult(result)
    score = score_object.get_view_dict()
    return render_template("cos_sim_field.html", score = score, field = field_result)

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Romantic of Text Mining{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet" >
<link href="{{ url_for('static', filename='css/self.css') }}" rel="stylesheet" >
{% endblock %}

{% block navbar %}
<nav class="navbar fixed-top navbar-expand-lg text-primary flex-row-reverse">
  <div class="navbar-brand-bg">
    <a class="navbar-brand" href="{{ url_for('main.index') }}">STARS Explorer</a>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse flex-row-reverse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('main.index') }}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Function
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{{ url_for('main.rank') }}">Rank</a>
          <a class="dropdown-item" href="{{ url_for('main.text_cloud') }}">Text Cloud</a>
          <a class="dropdown-item" href="{{ url_for('main.cos_sim') }}">Cos Similarity</a>
        </div>
      </li>
    </ul>
  </div>
</nav>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
</div>

  {% block page_content %}{% endblock %}

{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

app/templates/cos_sim.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Romantic of Text Mining{% endblock %}

{% block page_content %}
<div class="container main-content">
    <div class="container mt-4">
        <div class="func-figure-card row align-items-center">
            <div class="col-md-4 d-flex justify-content-center">
                <img class="img-responsive func_index" src="{{url_for('static', filename='assets/search-svgrepo-com.svg')}}" alt="Card image cap">
            </div>
            <div class="col-md-8 ps-4">
                <p class="align-self-center p-3">
                    <h1 class="text-primary" style="font-size:56px;">
                        <a href="{{ url_for('main.cos_sim') }}" class="text-decoration-none">Cos Similarity</a>
                    </h1>
                    <div class="index_function_content">Search contents in the selected field by keywords</div>
                    <form method="POST" action="{{ url_for('main.cos_sim') }}" style="font-size: 1.5rem;">
                        {{ search_form.csrf_token }}
                        <div>{{ search_form.field.label }} {{ search_form.field }}</div>
                        <div>{{ search_form.query.label }} {{ search_form.query(size=20) }}</div>
                        <div>{{ search_form.submit(class="btn btn-primary") }}</div>
                    </form>
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/cos_sim_field.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Romantic of Text Mining{% endblock %}

{% block page_content %}
<div class="container main-content">
    <div class="container" style="margin:2% auto">
        <div class="row field_section">
            <span class="category">
                <a href="{{ url_for('main.cos_sim') }}" class="text-decoration-none">Cos Similarity</a>
            </span>
            <h1 class="field_title">{{ field }}</h1>
        </div>
        <div class="row">
            {% for name, item in score.items() %}
            <div class="col-12 col-md-5 cos-sim-figure-card">
                <div class="cos-score-card-point text-danger">{{ item['score'] }}</div>
                <div class="rank-card-report-state" >
                    <div class="cos-score-card-level">{{ item['level'] }}</div>
                    <div class="cos-score-card-item">{{ item['item'] }}</div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/function_index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="container main-content">
    <div class="container mt-4">
        <div class="func-figure-card row align-items-center">
            <div class="col-md-4 d-flex justify-content-center">
                <img class="img-responsive func_index" src="{{url_for('static', filename='assets/rank-svgrepo-com.svg')}}" alt="Card image cap">
            </div>
            <div class="col-md-8 ps-4">
                <p>
                    <h1 class="text-primary" style="font-size:56px;">Ranking</h1>
                    <div class="index_function_content">Get the best content from the selected field.</div>
                    <a href="{{ url_for('main.rank') }}" class="btn btn-primary">Check</a>
                </p>
            </div>
        </div>
    </div>
    <div class="container mt-4">
        <div class="func-figure-card row align-items-center">
            <div class="col-md-4 d-flex justify-content-center">
                <img class="img-responsive func_index" src="{{url_for('static', filename='assets/cloud-svgrepo-com.svg')}}" alt="Card image cap">
            </div>
            <div class="col-md-8 ps-4">
                    <h1 class="text-primary" style="font-size:56px;">Text Cloud</h1>
                    <div class="index_function_content">Learn the key difference of the selected field in levels.</div>
                    <a href="{{ url_for('main.text_cloud') }}" class="btn btn-primary">Check</a>
                </p>
            </div>
        </div>
    </div>
    <div class="container mt-4">
        <div class="func-figure-card row align-items-center">
            <div class="col-md-4 d-flex justify-content-center">
                <img class="img-responsive func_index" src="{{url_for('static', filename='assets/search-svgrepo-com.svg')}}" alt="Card image cap">
            </div>
            <div class="col-md-8 ps-4">
                <p>
                    <h1 class="text-primary" style="font-size:56px;">Cos Similarity</h1>
                    <div class="index_function_content">Search contents in the selected field by keywords</div>
                    <a href="{{ url_for('main.cos_sim') }}" class="btn btn-primary">Check</a>
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="row mt-4">
    <div id="banner-container-left" class="col-12 col-md-5 align-items-center">
        <img src="../static/assets/SDG.png">
    </div>
    <div class="col-12 col-md-7 row" id="banner-container-right">
        <div class="banner-content col-12">
            <scan class="banner-slogan text-primary">Build Sustainability by Collective Wisdom from Top Universities.</scan>
        </div>
        <div class="banner-button mt-4 col-12">
            <a href="{{ url_for('main.function_index') }}" class="btn btn-primary m-auto index-btn">Learn More</a>
        </div>
    </div>
</div>
{% endblock %}

app/templates/rank.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Romantic of Text Mining{% endblock %}

{% block page_content %}
<div class="container main-content">
    <div class="container mt-4">
        <div class="func-figure-card row align-items-center">
            <div class="col-md-4 d-flex justify-content-center">
                <img class="img-responsive func_index" src="{{url_for('static', filename='assets/rank-svgrepo-com.svg')}}" alt="Card image cap">
            </div>
            <div class="col-md-8 ps-4">
                <p class="align-self-center p-3">
                    <h1 class="text-primary" style="font-size:56px;">
                        <a href="{{ url_for('main.rank') }}" class="text-decoration-none">Ranking</a>
                    </h1>
                    <div class="index_function_content">Get the best content from the selected field.</div>
                    <form method="POST" action="{{ url_for('main.rank') }}" style="font-size: 1.5rem;">
                        {{ form.csrf_token }}
                        {{ form.field.label }} {{ form.field }}
                        {{ form.submit(class='btn btn-primary') }}
                    </form>
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/rank_field.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Romantic of Text Mining{% endblock %}

{% block page_content %}
<div class="container main-content">
    <div class="container" style="margin:2% auto">
        <div class="row field_section">
            <a href="{{ url_for('main.rank') }}" class="text-decoration-none category">Ranking</a>
            <h1 class="field_title">{{ field }}</h1>
        </div>
        {% for item, sheet in rank_result.items() %}
            <div class="item-name">{{ item.capitalize() }}</div>
            <div class="row">
                {% for index, content in sheet.items() %}
                <div class="rank-figure-card">
                    <div class="row">
                        <div class="col-6 col-sm-4 col-lg-2 justify-content-center" >
                            <div class="rank-card-point-box">
                                <scan class="rank-card-point text-right text-danger">{{ content['Points Earned'] }}</scan>
                                <scan class="rank-card-total text-right">/{{ content['Available Points'] }}</scan>
                            </div>
                        </div>
                        <div class="col-6 col-sm-8 col-lg-10">
                            <div class="rank-card-report-state" ></div>
                                <scan class="rank-card-level">{{ content['Rated Level'] }}</scan>
                                <scan class="rank-card-version">ver. {{ content['STARS Version'] }}</scan>
                            <div class="rank-card-institute">{{ content['Institution'] }}</div>
                            <div class="rank-card-bg-institute mb-4">
                                <scan class="rank-card-country">{{ content['Country'] }}, </scan>
                                <scan class="rank-card-institute-type">{{ content['Institution Type'] }}</scan>
                            </div>
                            <div class="rank-card-summary">
                                <p class="collapse" id="collapseSummary_{{ index }}">{{ content['Description'] }}</p>
                                <a class="collapsed" data-toggle="collapse" href="#collapseSummary_{{ index }}" aria-expanded="false" aria-controls="collapseSummary_{{ index }}"></a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

app/templates/text_cloud.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Romantic of Text Mining{% endblock %}

{% block page_content %}
<div class="container main-content">
    <div class="container mt-4">
        <div class="func-figure-card row align-items-center">
            <div class="col-md-4 d-flex justify-content-center">
                <img class="img-responsive func_index" src="{{url_for('static', filename='assets/cloud-svgrepo-com.svg')}}" alt="Card image cap">
            </div>
            <div class="col-md-8 ps-4">
                <p class="align-self-center p-3">
                    <h1 class="text-primary" style="font-size:56px;">
                        <a href="{{ url_for('main.text_cloud') }}" class="text-decoration-none">Text Cloud</a>
                    </h1>
                    <div class="index_function_content">Learn the key difference of the selected field in levels.</div>
                    <form method="POST" action="{{ url_for('main.text_cloud') }}" style="font-size: 1.5rem;">
                        {{ form.csrf_token }}
                        {{ form.field.label }} {{ form.field }}
                        {{ form.submit(class='btn btn-primary') }}
                    </form>
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/text_cloud_field.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Romantic of Text Mining{% endblock %}
{% block page_content %}
<script src="../static/src/wordcloud2.js"></script>
<script src="../static/src/text_cloud.js"></script>

<div class="container main-content">
    <div class="container" style="margin:2% auto">
        <div class="row field_section">
            <a href="{{ url_for('main.text_cloud') }}" class="category text-decoration-none">Text Cloud</a>
            <h1 class="field_title">{{ field }}</h1>
        </div>
        <ul class="row">
            {% for level, content in result.items() %}
                <div class="col-6 figure">
                    <div class="figure-card">
                        <div id="canvas_{{ loop.index }}" class="tc_canvas"></div>
                        <script type="text/javascript">
                            var tagList_{{ loop.index }} = {{ content["tagList"]|tojson }}
                            generate_text_cloud("canvas_{{ loop.index }}", tagList_{{ loop.index }}, {{ content["minFreq"] }});
                        </script>
                        <div class="figure-card-description">
                            <div class="figure-card-title">{{ level.capitalize() }}</div>
                            <div class="tokens_quantity_section">
                                <scan class="var_tokens_quantity">word </scan>
                                <scan class="tokens_quantity">50</scan>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>
        </ul>
    </div>
</div>
{% endblock %}

app/templates/textcloud.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Romantic of Text Mining{% endblock %}

{% block page_content %}
<div class="container" style="margin:2% auto">
    <div class="row field_section">
        <span class="category">Text Cloud</span>
        <h1 class="field_title">Public Engagement</h1>
    </div>
    <ul class="row">
        {% for level in text_cloud.get_textclouds_level() %}
            <li class="col-6">
                <div class="figure-card">
                    <img class="img-responsive" src="../static/result/{{ level }}.png" alt="Card image cap">
                    <div class="figure-card-title">{{ level }}</div>
                    <div class="tokens_quantity_section">
                        <scan class="var_tokens_quantity">word </scan>
                        <scan class="tokens_quantity">50</scan>
                    </div>
                </div>
            </li>
        {% endfor %}
        </div>
    </ul>
</div>

{% endblock %}